{{- if and .Values.rbac.enabled .Values.rbac.serviceAccountCreate }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    app: {{ template "allure-testops.fullname" . }}
    chart: {{ template "allure-testops.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.storage.awsSTS.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.storage.awsSTS.arn }}"
{{- end }}
{{- end -}}
