apiVersion: v2
name: testops
version: 5.6.4
appVersion: 5.6.4

description: TestOps

kubeVersion: '>= 1.14.0-0'

home: https://qameta.io
sources:
  - https://github.com/qameta/testops-deploy-helm-chart

maintainers:
  - name: Alexey B.
    email: alexey.bogdanov@qameta.io
  - name: George I.
    email: egor.ivanov@qameta.io

dependencies:
  - name: rabbitmq
    version: 12.14.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.deployByChart
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.16.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.deployByChart
  - name: minio
    version: 13.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
