name: Lint and Test Charts

on:
  pull_request:

jobs:
  lint-test:
    runs-on: [ linux, cpu16 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
        with:
          version: v3.8.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --debug

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        timeout-minutes: 10
        run: |
          ct install --config ct.yaml --debug --helm-extra-set-args "--set=postgresql.enabled=true --set=minio.enabled=true --set=image.authRequired.enabled=true --set=image.registry=dl.qameta.io --set=image.repository=docker-internal --set=image.authRequired.username=${{ secrets.ARTIFACTORY_USER }} --set=image.authRequired.password=${{ secrets.ARTIFACTORY_PASS }}"
