name: Release Charts

#on:
#  push:
#    branches:
#      - main

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get version
        run: |
          CHART_VERSION=$(grep -m 1 '^version:' charts/testops/Chart.yaml | sed 's/version:[[:space:]]*//')
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Helm publish
        uses: qameta/artifactory-publisher@v1
        with:
          endpoint: https://dl.qameta.io/artifactory/helm/
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASS }}
          repoName: testops
          chart: charts/testops
          version: "${CHART_VERSION}"
